### ISSUE TITLE
UnsatisfiedLinkError: jnidispatch

### ISSUE THREAD

**Issue by duncangallimore** [Microsoft/vscode-iot-workbench#445]
Every time I install the Workbench in Code and restart I get this error in the Arduino Output window:
[Starting] Install package - esp32...
Exception in thread "main" java.lang.UnsatisfiedLinkError: jnidispatch (/com/sun/jna/win32-amd64/jnidispatch.dll) not found in resource path
	at com.sun.jna.Native.loadNativeLibrary(Native.java:471)
	at com.sun.jna.Native.<clinit>(Native.java:91)
	at processing.app.windows.Platform.<clinit>(Platform.java:280)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at processing.app.Base.initPlatform(Base.java:219)
	at processing.app.Base.main(Base.java:114)
[Done] Installed board package - esp32

Please help! I've tried everything I can think of. I've been through the install here:
https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/esp32/esp32-get-started.md
and tried uninstalling Code and reinstalling. If I remove Workbench and restart the error goes away.

Thanks, Duncan

**Comment by duncangallimore** [comment]
That's it! Thank you!
