### ISSUE TITLE
can not upload sketch to board

### ISSUE THREAD

**Issue by StephaneDelcroix** [Microsoft/vscode-iot-workbench#592]
```
[Starting] Upload sketch - GetStarted.ino
Please see the build logs in Output path: /Users/...
java.lang.NullPointerException
	at processing.app.BaseNoGui.selectSerialPort(BaseNoGui.java:1088)
	at processing.app.helpers.CommandlineParser.parseArgumentsPhase1(CommandlineParser.java:143)
	at processing.app.Base.<init>(Base.java:273)
	at processing.app.Base.guardedMain(Base.java:219)
	at processing.app.Base.main(Base.java:132)
```

using arduino 1.8.9 on mac

**Comment by StephaneDelcroix** [comment]
my wrong. I had multiple Arduino IDE installed
